[Interface]
Address = 192.168.6.33/32
DNS = 1.1.1.1,8.8.8.8
PrivateKey = KDKj2gDKyBRnwKtUaynl4wa2++t+1g7uOcVnug7OpUo=
[Peer]
publickey=WHDJ0JEVhQAzzzyEYZ7igs1MW2ypjwJ7YmjbEdjutiY=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = se2.vpnjantit.com:1024
